# Docker Compose Override Example for Local Development
# 
# Copy this file to docker-compose.override.yml to enable local development features:
#   cp docker-compose.override.yml.example docker-compose.override.yml
#
# This override:
# 1. Runs /quant-entrypoint.d/ scripts (like 00-copy-drupal-cms.sh) on container startup
# 2. Sets database environment variables for local MySQL container
#
# In production (Quant Cloud), the platform wrapper handles entrypoints automatically.

services:
  drupal-cms:
    # Override entrypoint for local dev to run /quant-entrypoint.d/ scripts
    # This copies Drupal CMS source to the persistent volume on first boot
    entrypoint: ["/usr/local/bin/docker-entrypoint-drupal-cms.sh"]
    command: ["apache2-foreground"]
    
    volumes:
      # Mount entire src directory for local development
      - ./src:/opt/drupal
      # Mount dev PHP config to override production settings (zz- prefix ensures it loads last)
      - ./dev-php.ini:/usr/local/etc/php/conf.d/zz-dev.ini:ro
    
    # Set environment variables for local development
    environment:
      - QUANT_ENV_TYPE=development
      - DB_HOST=mysql
      - DB_DATABASE=drupal
      - DB_USERNAME=drupal
      - DB_PASSWORD=drupal
      - DB_PORT=3306
      - DISABLE_DB_TLS=true
      - DRUPAL_HASH_SALT=local-dev-salt-change-in-production

  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
