name: Test codebases

on:
  - push

env:
  NODE_ENV: development

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-drupal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mysql, pgsql, gd, zip, opcache, redis, apcu

      - name: Install project dependencies
        run: composer install --working-dir=./src --dev

      - name: Install dependencies
        run: |
          composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer global require --dev -n "squizlabs/php_codesniffer=*"
          composer global require --dev -n drupal/coder

      - name: Validate code standards
        run: phpcs --standard=./src/phpcs.xml
