name: Test codebases

on:
  - push

env:
  NODE_ENV: development

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-drupal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mysql, pgsql, gd, zip, opcache, redis, apcu

      - name: Install project dependencies
        run: composer install --working-dir=./src --dev

      - name: Validate code standards
        run: ./src/vendor/bin/phpcs --standard=./src/phpcs.xml
